#!/usr/bin/env python
# encoding: utf-8


def triangular_product_calculate(products: list, separator: str) -> list:
    triangular_list = list()
    for product in products:
        excluded_products = set(products) - {product}
        currencies = product.split(separator)
        next_products_set = set([p for p in excluded_products if currencies[0] in p.split(separator)])
        for product2 in next_products_set:
            currencies2 = product2.split(separator)
            if currencies[0] == currencies2[0]:
                another_currency = currencies2[1]
            elif currencies[0] == currencies2[1]:
                another_currency = currencies2[0]
            else:
                another_currency = ""
            if separator.join([currencies[1], another_currency]) in products:
                triangular_list.append([product, product2, separator.join([currencies[1], another_currency])])
            if separator.join([another_currency, currencies[1]]) in products:
                triangular_list.append([product, product2, separator.join([another_currency, currencies[1]])])
    return triangular_list


if __name__ == "__main__":
    xt_products = ["tyv_usdt", "mir_usdt", "ape_usdt", "kycc_usdt", "tpy_usdt", "stg_usdt", "brg_usdt", "snack_usdt",
                   "cml_usdt", "btc_dai", "eth_dai", "stos_usdt", "caw_usdt", "elon_usdt", "cro_usdt", "bend_usdt",
                   "xrd_usdt", "dogecube_usdt", "egx_usdt", "pando_usdt", "strm_usdt", "rei_usdt", "gst_usdt",
                   "ceji_usdt",
                   "santos_usdt", "lazio_usdt", "ada_xt", "link_xt", "ltc_xt", "matic_xt", "sol_xt", "qnt_usdt",
                   "stx_usdt", "astr_usdt", "bnb_xt", "iost_usdt", "juv_usdt", "wemix_usdt", "lunc_usdt", "ustc_usdt",
                   "jst_usdt", "op_usdt", "waxp_usdt", "snt_usdt", "waves_usdt", "grv_usdt", "hbar_usdt", "mat_usdt",
                   "neeo_usdt", "pundix_usdt", "shit_usdt", "b8t_usdt", "unfi_usdt", "ctsi_usdt", "movez_usdt",
                   "ray_usdt",
                   "xtal_usdt", "flux_usdt", "lof_usdt", "twt_usdt", "gtcoin_usdt", "well_usdt", "fort_usdt", "sol_btc",
                   "matic_btc", "crv_btc", "dot_btc", "near_btc", "mana_btc", "link_btc", "knc_btc", "ksm_btc",
                   "mmt_usdt",
                   "bibl_usdt", "saitama(v2)_usdt", "g_usdt", "kwave_usdt", "bnd_usdt", "xtusd_usdt", "btc_xtusd",
                   "eth_xtusd", "cleg_usdt", "glu_usdt", "cep_usdt", "locus_usdt", "ssx_usdt", "gmx_usdt", "mcd_usdt",
                   "quint_usdt", "redlc_usdt", "rvn_usdt", "psg_usdt", "ethw_usdt", "tbc_usdt", "zax_usdt",
                   "lever_usdt",
                   "carac_usdt", "neox_usdt", "omax_usdt", "gami_usdt", "brn_usdt", "qie_usdt", "sweat_usdt",
                   "pop_usdt",
                   "1mmmit_usdt", "smpc_usdt", "aleo(iou)_usdt", "jk_usdt", "links_usdt", "prmx_usdt", "xen_usdt",
                   "tama_usdt", "bxen_usdt", "apt_usdt", "vinu_usdt", "srlty_usdt", "heaven_usdt", "yes1_usdt",
                   "strm_btc",
                   "sui_usdt", "creta_usdt", "bgvt_usdt", "hft_usdt", "mooney_usdt", "bigp_usdt", "gala_usdt",
                   "tri_usdt",
                   "rune_usdt", "glm_usdt", "amp_usdt", "kub_usdt", "vidt_usdt", "vgx_usdt", "fun_usdt", "mdx_usdt",
                   "est_usdt", "reef_usdt", "rlc_usdt", "dent_usdt", "cfx_usdt", "pha_usdt", "strax_usdt", "qkc_usdt",
                   "nkn_usdt", "iq_usdt", "stpt_usdt", "stmx_usdt", "vtho_usdt", "beta_usdt", "tkg_usdt", "agix_usdt",
                   "sun_usdt", "multi_usdt", "rif_usdt", "lto_usdt", "arpa_usdt", "alpaca_usdt", "lina_usdt",
                   "chess_usdt",
                   "tru_usdt", "firo_usdt", "kmd_usdt", "phb_usdt", "vanry_usdt", "data_usdt", "ata_usdt", "adx_usdt",
                   "om_usdt", "fis_usdt", "agld_usdt", "epx_usdt", "mbl_usdt", "ooki_usdt", "gft_usdt", "drep_usdt",
                   "torn_usdt", "akro_usdt", "dego_usdt", "yes1_usdc", "syn_usdt", "xyo_usdt", "aioz_usdt",
                   "aleph_usdt",
                   "prq_usdt", "math_usdt", "nct_usdt", "krl_usdt", "qsp_usdt", "crpt_usdt", "png_usdt", "sylo_usdt",
                   "swftc_usdt", "fwc_usdt", "mlxc_usdt", "dyp_usdt", "muse_usdt", "mnde_usdt", "orca_usdt", "oax_usdt",
                   "c98_btc", "ast_btc", "btc_usdt", "eth_usdt", "etc_usdt", "ltc_usdt", "ada_usdt", "chz_btc",
                   "eos_usdt",
                   "xrp_usdt", "xlm_usdt", "xem_usdt", "dash_usdt", "bts_usdt", "xwc_usdt", "agld_btc", "eth_btc",
                   "etc_btc", "ltc_btc", "ada_btc", "eos_btc", "xrp_btc", "xlm_btc", "dash_btc", "xt_usdt", "xt_btc",
                   "phb_btc", "doge_usdt", "doge_btc", "cfx_btc", "tru_btc", "firo_btc", "chess_btc", "qi_btc",
                   "bmt_usdt",
                   "cleg_btc", "walv_usdt", "nxt_usdt", "omax_bnb", "sc_usdt", "dcr_usdt", "dcr_btc", "lina_btc",
                   "qtum_usdt", "qtum_btc", "xtz_usdt", "xtz_btc", "fil_btc", "bsv_usdt", "zec_usdt", "sol_eth",
                   "bat_usdt", "blkc_usdt", "neo_usdt", "neo_btc", "omg_usdt", "iota_eth", "xfl_usdt", "han_usdt",
                   "xspectar_usdt", "pi_usdt", "bonk_usdt", "gymnet_usdt", "gymnet_bnb", "debt_usdt", "wsi_usdt",
                   "samo_usdt", "tel_usdt", "rond_usdt", "ton_usdt", "kok_usdt", "shill_usdt", "sfund_usdt", "zbc_usdt",
                   "ertha_usdt", "flr_usdt", "cmp_usdt", "ctc_usdt", "primal_usdt", "dfi_usdt", "vra_usdt", "hook_usdt",
                   "ipv_usdt", "bone_usdt", "jpeg_usdt", "floki_usdt", "toko_usdt", "wild_usdt", "imgnai_usdt",
                   "dc_usdt",
                   "bscpad_usdt", "gq_usdt", "orai_usdt", "core_usdt", "bdp_usdt", "dafi_usdt", "kata_usdt", "vai_usdt",
                   "hlpr_usdt", "gns_usdt", "rdnt_usdt", "paw_usdt", "nftb_usdt", "ali_usdt", "ufo_usdt", "blur_usdt",
                   "abp_usdt", "sinso_usdt", "btc2_usdt", "alu_usdt", "vvs_usdt", "trava_usdt", "hyper_usdt",
                   "zrx_usdt",
                   "cult_usdt", "lyx_usdt", "metav_usdt", "mepad_usdt", "metaf_usdt", "fund_usdt", "blink_usdt",
                   "vela_usdt", "5mc_usdt", "btx_usdt", "memag_usdt", "phl_usdt", "lqty_usdt", "vnxau_usdt",
                   "vnxau_btc",
                   "vnxau_eth", "vchf_usdt", "vchf_btc", "vchf_eth", "veur_usdt", "trx_usdt", "veur_btc", "veur_eth",
                   "trx_btc", "d2t_usdt", "kas_usdt", "arb_usdt", "id_usdt", "ktc_usdt", "zz_usdt", "frin_usdt",
                   "pendle_usdt", "ftn_usdt", "fght_usdt", "xact_usdt", "mom_usdt", "myria_usdt", "agi_usdt",
                   "play_usdt",
                   "mtb_usdt", "crown_usdt", "aidoge_usdt", "shibai_usdt", "aped_usdt", "dxgm_usdt", "rekt_usdt",
                   "iron_usdt", "xspectar_btc", "xspectar_eth", "jot_usdt", "edu_usdt", "metro_usdt", "met_usdt",
                   "wojak_usdt", "clips_usdt", "turbo_usdt", "pepe_usdt", "zix_usdt", "bob_usdt", "zpc_usdt",
                   "ordi_usdt",
                   "dino_usdt", "vmpx_usdt", "nals_usdt", "piza_usdt", "pepebrc_usdt", "noot_usdt", "moon_usdt",
                   "cetus_usdt", "drac_usdt", "bsvbrc_usdt", "diba_usdt", "trac_usdt", "ozft_usdt", "simpson_usdt",
                   "sponge_usdt", "dogeceo_usdt", "suia_usdt", "turbos_usdt", "mto_usdt", "rfd_usdt", "qub_usdt",
                   "agb_usdt", "nrk_usdt", "xaut_usdt", "eurt_usdt", "golc_usdt", "wagmigames_usdt", "aavel_usdt",
                   "stbu_usdt", "omn_usdt", "awt_usdt", "ciri_usdt", "lyum_usdt", "quv_usdt", "arkm_usdt", "iluc_usdt",
                   "wld_usdt", "mmvg_usdt", "x_usdt", "edlc_usdt", "edlc_btc", "tlos_usdt", "sei_usdt", "mhlk_usdt",
                   "mhlk_btc", "cyber_usdt", "x(crux)_usdt", "rss3_usdt", "opv_usdt", "hxa_usdt", "dreams_usdt",
                   "ca_usdt",
                   "logan_usdt", "sald_usdt", "eva_usdt", "simp_usdt", "tril_usdt", "yesgo_usdt", "memetoon_usdt",
                   "bzet_usdt", "mlxv_usdt", "ctex_usdt", "daw_usdt", "ator_usdt", "bigtime_usdt", "ntrn_usdt",
                   "orbs_usdt", "dome_usdt", "qgold_usdt", "aia_usdt", "qgold_btc", "naka_usdt", "fxy_usdt",
                   "krest_usdt",
                   "joy153_usdt", "tia_usdt", "memecoin_usdt", "mnt_usdt", "leo_usdt", "sats_usdt", "beamx_usdt",
                   "party_usdt", "ato_usdt", "abel_usdt", "cad_usdt", "cvtx_usdt", "xert_usdt", "xpe_usdt", "smh_usdt",
                   "dexnet_usdt", "rats_usdt", "pyth_usdt", "rat_usdt", "myro_usdt", "velodrome_usdt", "satox_usdt",
                   "zeph_usdt", "pit_usdt", "bssb_usdt", "yec_usdt", "btcsn_usdt", "space_usdt", "tet_usdt", "rxd_usdt",
                   "clore_usdt", "xpet_usdt", "pays_usdt", "pmpy_usdt", "soh_usdt", "turt_usdt", "gdag_usdt",
                   "p3d_usdt",
                   "eti_usdt", "rtc_usdt", "alienb_usdt", "jto_usdt", "music_usdt", "btcs_usdt", "btn_usdt",
                   "coda_usdt",
                   "cts2_usdt", "memeetf_usdt", "pmg_usdt", "ubdn_usdt", "aitech_usdt", "kls_usdt", "riso_usdt",
                   "cheel_usdt", "maximus_usdt", "zero_usdt", "dimo_usdt", "ace_usdt", "lila_usdt", "fact_usdt",
                   "kiiro_usdt", "mubi_usdt", "mice_usdt", "mmss_usdt", "bnsx_usdt", "rdex_usdt", "dova_usdt",
                   "1cat_usdt",
                   "eac_usdt", "ksta_usdt", "mobile_usdt", "honey_usdt", "hnt_usdt", "efil_usdt", "com_usdt",
                   "deed_usdt",
                   "chax_usdt", "dovi_usdt", "csas_usdt", "dswp_usdt", "biis_usdt", "dio_usdt", "fxy_inr", "retro_usdt",
                   "16dao_usdt", "coq_usdt", "bear_usdt", "silly_usdt", "knob_usdt", "dio_usdc", "mimic_usdt",
                   "nam_usdt",
                   "pyi_usdt", "when_usdt", "alfa_usdt", "boo_usdt", "asct_usdt", "vkye_usdt", "avav_usdt", "egg_usdt",
                   "imeta_usdt", "hut_usdt", "pivx_usdt", "alfa_eth", "alfa_btc", "sobb_usdt", "ords_usdt", "carb_usdt",
                   "degen_usdt", "nfp_usdt", "trb_usdt", "oftn_usdt", "rabbit_usdt", "saix_usdt", "3ull_usdt",
                   "snmt_usdt",
                   "cng_usdt", "netz_usdt", "dozy_usdt", "cgpt_usdt", "pika_usdt", "lords_usdt", "olas_usdt",
                   "xai_usdt",
                   "unct_usdt", "xd_usdt", "atoplus_usdt", "ckp_usdt", "game_usdt", "sols_usdt", "wif_usdt", "crl_usdt",
                   "1000troll_usdt", "sshib_usdt", "peas_usdt", "zuzalu_usdt", "1msmiley_usdt", "speero_usdt",
                   "gamer_usdt", "kirby_usdt", "nett_usdt", "tcati_usdt", "ondo_usdt", "eacc_usdt", "nobody_usdt",
                   "jup_usdt", "alt_usdt", "snst_usdt", "islm_usdt", "mwcc_usdt", "ron_usdt", "ramsena_usdt",
                   "manta_usdt",
                   "dym_usdt", "wys_usdt", "kna_usdt", "area_usdt", "mockjup_usdt", "far_usdt", "myra_usdt",
                   "camly_usdt",
                   "flip_usdt", "babybonk_usdt", "wen_usdt", "rwas_usdt", "bitbedr_usdt", "ponke_usdt", "cvip_usdt",
                   "gme_usdt", "pork_usdt", "duel_usdt", "usdt_inr", "metis-bsc_usdt", "zeta_usdt", "nuts_usdt",
                   "ins_usdt", "fanx_usdt", "banana_usdt", "altl_usdt", "unmd_usdt", "degen1_usdt", "slk_usdt",
                   "aero_usdt", "blast_usdt", "ava_usdt", "long_usdt", "joy_usdt", "pandora_usdt", "anon_usdt",
                   "defrogs_usdt", "rug_usdt", "pixel_usdt", "avtm_usdt", "xsci_usdt", "strk_usdt", "gtai_usdt",
                   "grok_usdt", "zkf_usdt", "ac_usdt", "sora_usdt", "mog_usdt", "ornj_usdt", "htx_usdt", "ai_usdt",
                   "lsd_usdt", "bcut_usdt", "fp_usdt", "sln_usdt", "prom_usdt", "gpt_usdt", "sheb_usdt", "portal_usdt",
                   "astx_usdt", "pdx1_usdt", "voya_usdt", "xrgb_usdt", "quark_usdt", "akt_usdt", "parcl_usdt",
                   "hdn_usdt",
                   "emerald_usdt", "aiepk_usdt", "aibb_usdt", "ctk_usdt", "faya_usdt", "aisc_usdt", "amu_usdt",
                   "navi_usdt", "aog_usdt", "app_usdt", "arty_usdt", "asm_usdt", "astra_usdt", "babygrok_usdt",
                   "w_usdt",
                   "vdo_usdt", "flt_usdt", "blok_usdt", "boson_usdt", "brct_usdt", "brwl_usdt", "caga_usdt",
                   "monai_usdt",
                   "yes_usdt", "metas_usdt", "kep_usdt", "nao_usdt", "ceek_usdt", "cell_usdt", "cere_usdt", "cfg_usdt",
                   "chapz_usdt", "ryoshi_usdt", "ethpi_usdt", "combo_usdt", "copi_usdt", "cpool_usdt", "cre_usdt",
                   "cru_usdt", "plx_usdt", "blendr_usdt", "unix_usdt", "col_usdt", "csix_usdt", "cudos_usdt",
                   "cummies_usdt", "cweb_usdt", "dcb_usdt", "doi_usdt", "scarcity_usdt", "tao_usdt", "mona_usdt",
                   "hemule_usdt", "gekko_usdt", "derc_usdt", "dmtr_usdt", "huge_usdt", "dck_usdt", "fet_usdt",
                   "nos_usdt",
                   "sns_usdt", "palm_usdt", "trac1_usdt", "dka_usdt", "rtc7_usdt", "cbk_usdt", "ever_usdt", "fuse_usdt",
                   "aevo_usdt", "epep_usdt", "brett_usdt", "tonup_usdt", "sync_usdt", "spacepi_usdt", "vsys_usdt",
                   "knc_usdt", "xmr_usdt", "lrc_usdt", "storj_usdt", "zil_usdt", "lsk_btc", "atom_usdt", "lsk_usdt",
                   "ont_usdt", "ont_btc", "algo_usdt", "algo_btc", "eth_xt", "bna_usdt", "tusd_usdt", "hex_usdt",
                   "ckb_usdt", "gmm_usdt", "usdc_usdt", "link_usdt", "band_usdt", "ast_usdt", "snx_usdt", "bal_usdt",
                   "mkr_usdt", "comp_usdt", "dia_usdt", "dai_usdt", "for_usdt", "uma_usdt", "nmr_usdt", "rsr_usdt",
                   "dot_usdt", "kava_usdt", "sushi_usdt", "crv_usdt", "pnt_usdt", "uni_usdt", "tp_usdt", "zen_usdt",
                   "api3_usdt", "aave_usdt", "front_usdt", "el_usdt", "tbcc_usdt", "1inch_usdt", "fxs_usdt", "bnb_usdt",
                   "okb_usdt", "pc_usdt", "fil_usdt", "mana_usdt", "matic_usdt", "oks_usdt", "sand_usdt", "dodo_usdt",
                   "mask_usdt", "klv_usdt", "hgold_usdt", "bitci_usdt", "wdc_usdt", "ilv_usdt", "shib_usdt",
                   "akita_usdt",
                   "link_eth", "forth_usdt", "ankr_usdt", "enj_usdt", "chz_usdt", "cvc_usdt", "loom_usdt", "grt_usdt",
                   "skl_usdt", "ogn_usdt", "xch_usdt", "icp_usdt", "cspr_usdt", "xusd_usdt", "bzz_usdt", "ham_usdt",
                   "ksm_usdt", "ern_usdt", "cqt_usdt", "babydoge_usdt", "minidoge_usdt", "luna_usdt", "theta_usdt",
                   "ftm_usdt", "axs_usdt", "brise_usdt", "ygg_usdt", "star_usdt", "aave_eth", "xrp_eth", "ada_eth",
                   "theta_eth", "trx_eth", "hrdg_usdt", "mina_usdt", "swt_usdt", "sol_usdt", "vet_usdt", "frts_usdt",
                   "del_usdt", "del_btc", "mbox_usdt", "1000000hvi_usdt", "1000kquack_usdt", "saitama_usdt", "ldo_usdt",
                   "alice_usdt", "tlm_usdt", "rare_usdt", "bel_usdt", "kom_usdt", "luffy_usdt", "dydx_usdt", "inj_usdt",
                   "celr_usdt", "hzm_usdt", "btc_usdc", "eth_usdc", "avax_usdt", "ewc_usdt", "free_usdt", "erw_usdt",
                   "near_usdt", "one_usdt", "klay_usdt", "shib_doge", "cind_usdt", "atlas_usdt", "raca_usdt",
                   "cake_usdt",
                   "slp_usdt", "ens_usdt", "ets_usdt", "perp_usdt", "ijz_usdt", "qi_usdt", "gm_usdt", "chr_usdt",
                   "iotx_usdt", "win_usdt", "rndr_usdt", "imx_usdt", "jasmy_usdt", "ssv_usdt", "boba_usdt", "gel_usdt",
                   "baby_usdt", "invi_usdt", "woo_usdt", "people_usdt", "abbc_usdt", "sfp_usdt", "rpl_usdt",
                   "xmon_usdt",
                   "ftt_usdt", "mdt_usdt", "voxel_usdt", "freerossdao_usdt", "high_usdt", "ocean_usdt", "c98_usdt",
                   "sos_usdt", "metis_usdt", "spell_usdt", "gas_usdt", "pokt_usdt", "looks_usdt", "burger_usdt",
                   "loka_usdt", "xld_usdt", "lpt_usdt", "ar_usdt", "seba_usdt", "iota_usdt", "hot_usdt", "rose_usdt",
                   "egld_usdt", "flow_usdt", "celt_usdt", "1bshibdoge_usdt", "ach_usdt", "joe_usdt", "anc_usdt",
                   "bch_usdt", "bch_btc", "fida_usdt", "x2y2_usdt", "dingo_usdt", "t_usdt", "magic_usdt", "solo_usdt",
                   "tfuel_usdt", "a1a_usdt", "kunci_usdt", "fio_usdt", "prm_usdt", "glmr_usdt", "gmt_usdt", "loop_usdt"]
    xt_triangular_list = triangular_product_calculate(xt_products, "_")
    print(xt_triangular_list)
    print(len(xt_triangular_list))
